### ISSUE TITLE
Bikeshed on @SideTag

### ISSUE THREAD

**Issue by munificent** [sigmundch/DEP-member-interceptors#4]
The name is a bit strange because "tag" isn't used anywhere else. I don't think it's really relevant to this proposal anyway, but how about `@ApplyAnnotationTo` or just `@Annotate`?

**Comment by jakemac53** [comment]
It might be best to just remove all mentions of @SideTag from this proposal, and separate it out into its own DEP

**Comment by sigmundch** [comment]
thanks, good point, I renamed it to `@ApplyInterceptorTo`.

@jakemac53 while I agree that this doesn't need to be in right away, I think its good to discuss it in the proposal because it helps consider the tradeoffs between using annotations or a dedicated syntax. If we use a dedicated syntax, we'd have to add yet another syntax to do annotations on the side.
